apiVersion: v1
kind: ServiceAccount
metadata:
  name: blob-reorg-sa
  namespace: ad-bidding-analytics-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blob-reorg-role
  namespace: ad-bidding-analytics-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["minio-creds"]
  verbs: ["get", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blob-reorg-role-binding
  namespace: ad-bidding-analytics-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
- kind: ServiceAccount
  name: blob-reorg-sa
  namespace: ad-bidding-analytics-kafka
roleRef:
  kind: Role
  name: blob-reorg-role
  apiGroup: rbac.authorization.k8s.io